In [1]:
import pandas as pd, openpyxl
import os, sys, json
from datetime import datetime
with open("config.json", "r") as archivo:
    config_json = json.load(archivo)

Configuracion

In [2]:
month = 3
year = 2025

In [3]:
# Obtenemos el nombre del mes con los datos ingresados
date = f"{month}-{year}"
date = datetime.strptime(date,"%m-%Y")
month_str = datetime.strftime(date, "%B")

# Armamos el nombre del archivo
nombre_input = f"{month_str} {year}.xlsx"

In [4]:
# Consumimos novedades
novedades = pd.read_excel(f"{config_json['ruta_inputs']}Novedades {nombre_input}")

# Eliminamos las columnas que no nos sirven
novedades = novedades.drop(axis=1, columns={'Documento', 'Apellido', 'Nombre', 'OBSERVACIONES', 
                                            'Fecha baja', 'Fecha alta'})
novedades.head()

,Legajo,Basico,D. Enfermedad,Vacaciones,Feriado,Licencia,D. Mudanza,D. Estudio,D. Suspension,D. Tramite,Falta Inj.,Hs Extras,Dep. Judicial,Prepaga,Enlazados,Ant. de Sueldos,Adic. Ventas
0,1365,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1905,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1906,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2078,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
resultado = [] # Creamos una cadena vacia

# Iteramos las filas como series de pandas
for _,row in novedades.iterrows():
    # Iteramos las columnas del df
    for col in novedades.columns:    
        # Condicionamos a que las celdas que necesitamos no esten vacias excluyendo la de Legajo
        if col != 'Legajo' and not pd.isna(row[col]):  # Evitamos leer la columna Legajo
            resultado.append({
                "Empresa" : 1571,
                "Legajo": row['Legajo'],
                "Periodo": year,
                "Mes" : month,
                "Columna": col,
                "MesAjuste" : month,
                "Forzado" : 0,
                "Unidades": row[col],
                "Importe" : 0
            })

# Convertimos el resultado en Dataframe
df_resultado = pd.DataFrame(resultado)

# Establecemos el tipo de dato adecuado para cada columna
df_resultado['Legajo'] = df_resultado['Legajo'].astype(int)
df_resultado['Unidades'] = df_resultado['Unidades'].astype(int)

# Ordenamos de mayor a menor los valores del legajo para tener juntos los asesores
df_resultado.sort_values(by="Legajo", ascending=True)

# Verifiacamos que no hayan datos vacios
valores_vacios = df_resultado.isna().sum()
print(valores_vacios)

df_resultado.head() # Mostramos el envabezado

Empresa      0
Legajo       0
Periodo      0
Mes          0
Columna      0
MesAjuste    0
Forzado      0
Unidades     0
Importe      0
dtype: int64

,Empresa,Legajo,Periodo,Mes,Columna,MesAjuste,Forzado,Unidades,Importe
0,1571,1365,2025,3,D. Enfermedad,3,0,2,0
1,1571,1905,2025,3,Basico,3,0,6,0
2,1571,2078,2025,3,Basico,3,0,10,0
3,1571,1187,2025,3,Basico,3,0,18,0
4,1571,1980,2025,3,D. Enfermedad,3,0,4,0

In [6]:
#Exportar 
df_resultado.to_excel(f"{config_json['ruta_inputs']}Esueldos {nombre_input}",sheet_name="E-sueldos", index=False)